In [1]:
what_were_covered = [ 
    '1. end-to-end sklearn workflow',
    '2. Getting the data ready',
    '3. Choose the right estimator/algorithem for our problems',
    '4. fit he model/algorithem and use it to make predictions',
    '5. Evaluating the model',
    '6. Improve the model',
    '7. save and load a train model',
    '8. putting it all together']

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 4. fit he model/algorithem and use it to make predictions

#### 4.1 Fitting the model to the data

In [7]:
heart_disease = pd.read_csv('heart-disease.csv')

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8524590163934426

#### 4.2 make predictions using machine learning model
two ways to make predictions:
1. use `predict()`
2. use `predict_proba()`

##### `Predict()`

In [13]:
## Use a Trainned model to make predictions.
model.predict(np.array([1,2,4,5,6]))

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 4. 5. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [14]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [15]:
model.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [16]:
## Compare the predictions to truth table to evaluate the model


In [17]:
y_predic = model.predict(X_test)
np.mean(y_predic == y_test)

0.8524590163934426

In [18]:
## comparing np.mean() with model.score

model.score(X_test, y_test)

0.8524590163934426

In [19]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_predic)

0.8524590163934426

###### `Predict_proba()`

In [21]:
# Make predictions with predict_proba()
# predict_proba() returns probabilities of a classification label

##### `Predict()` can be used for regression models

In [24]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

boston = load_boston()

In [25]:
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [26]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = boston_df.drop('target', axis=1)
y = boston_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestRegressor().fit(X_train, y_train)

y_preds = model.predict(X_test)

In [27]:
y_preds[:5]

array([23.081, 30.574, 16.759, 23.46 , 16.893])

In [28]:
np.array(y_test[:5])

array([23.6, 32.4, 13.6, 22.8, 16.1])

In [29]:
## Compare the prediction to the truth
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, y_preds)

2.136382352941176